services:
  web:
    container_name: url-shortener-web-app
    image: ${DOCKER_REGISTRY}/url-shortener-web-app:latest
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    network_mode: "host"
    develop:
      watch:
        - action: sync
          path: .
          target: /code