services:
  app:
    container_name: app
    image: wsscottca/url-shortener-web-app:latest
    build: ./app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app

  caddy:
    container_name: caddy
    restart: unless-stopped
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    depends_on:
      - app
    environment:
      PROXY_BACKEND: app
      PROXY_PORT: 8000
      DOMAIN: ${DOMAIN}

volumes:
  caddy_data:
  caddy_config: